import os
import subprocess
import sys
import shutil

DIAGRAM_FILES = [
    "full_wiring_diagram.yaml",
    "brief_wiring_diagram.yaml",
    "brief_proto_routing_wiring_diagram.yaml",
    "brief_proto_power_only_wiring_diagram.yaml",
]

# Extensions generated by wireviz that we don't want to keep
CLEANUP_EXTENSIONS = [".svg", ".html", ".bom.tsv", ".gv"]


def run_command(command, cwd=None, use_sudo=False):
    if use_sudo:
        command = ["sudo"] + command
    print(f"Running: {' '.join(command)}")

    if use_sudo:
        result = subprocess.run(command, cwd=cwd)
        return result.returncode == 0, ""

    result = subprocess.run(command, cwd=cwd, capture_output=True, text=True)

    if result.stdout:
        print(f"Output: {result.stdout}")
    if result.stderr:
        print(f"Stderr: {result.stderr}")

    if result.returncode != 0:
        return False, result.stderr

    return True, result.stdout


def main():
    wiring_dir = os.path.dirname(os.path.abspath(__file__))
    venv_dir = os.path.join(wiring_dir, "venv")

    # 1. Create venv if it doesn't exist
    if not os.path.exists(venv_dir):
        print("Creating virtual environment...")
        run_command([sys.executable, "-m", "venv", venv_dir])

    # 2. Paths for pip and wireviz inside venv
    if os.name == "nt":
        pip_path = os.path.join(venv_dir, "Scripts", "pip")
        wireviz_path = os.path.join(venv_dir, "Scripts", "wireviz")
    else:
        pip_path = os.path.join(venv_dir, "bin", "pip")
        wireviz_path = os.path.join(venv_dir, "bin", "wireviz")

    # 3. Install dependencies
    print("Ensuring dependencies are installed in venv...")
    run_command([pip_path, "install", "graphviz", "wireviz", "pyyaml"])

    # 4. Check system graphviz
    if not shutil.which("dot"):
        print("Graphviz (dot) not found. Attempting to install...")
        if sys.platform.startswith("linux"):
            success, _ = run_command(["apt-get", "update"], use_sudo=True)
            if success:
                success, _ = run_command(["apt-get", "install", "-y", "graphviz"], use_sudo=True)
            if not success:
                print("Failed to install graphviz. Please run: sudo apt install graphviz")
                sys.exit(1)
        else:
            print("Please install graphviz manually (e.g. 'brew install graphviz')")
            sys.exit(1)

    # 5. Generate each diagram
    all_success = True
    for filename in DIAGRAM_FILES:
        diagram_file = os.path.join(wiring_dir, filename)

        if not os.path.exists(diagram_file):
            print(f"\nWarning: {filename} not found, skipping.")
            continue

        print(f"\n{'='*60}")
        print(f"Generating: {filename}")
        print(f"{'='*60}")

        success, _ = run_command([wireviz_path, filename], cwd=wiring_dir)

        if success:
            stem = filename.replace(".yaml", "")
            print(f"  -> {stem}.png")

            # Delete all non-PNG outputs
            for ext in CLEANUP_EXTENSIONS:
                path = os.path.join(wiring_dir, stem + ext)
                if os.path.exists(path):
                    os.remove(path)
        else:
            print(f"ERROR generating {filename}!")
            all_success = False

    if all_success:
        print(f"\n{'='*60}")
        print("All diagrams generated successfully (PNG only).")
        print(f"{'='*60}")
    else:
        print(f"\n{'='*60}")
        print("Some diagrams failed. See errors above.")
        print(f"{'='*60}")
        sys.exit(1)


if __name__ == "__main__":
    main()
